"""
Type stubs for shaaha's stable top-level public API.

Deliberately does NOT type `shaaha.<domain>` submodules (shaaha.math,
shaaha.ml, ...) - those are dynamic proxies whose real backend is chosen
at runtime based on what's installed and the host's hardware, so any
static type would either be dishonest (pretending it's always numpy, say)
or useless (Any). Faking that would be worse than leaving it untyped; use
shaaha.diagnose("<domain>") to see what a given proxy will actually
resolve to on your machine.
"""
from typing import Any, Optional

__version__: str
__author__: str
__license__: str
suppress_warnings: bool

def configure(
    prefer_gpu: bool = ...,
    auto_install: bool = ...,
    log_level: str = ...,
    force_backend: Optional[dict[str, str]] = ...,
) -> None: ...
def status() -> dict[str, Any]: ...
def available_backends(domain: str) -> list[str]: ...
def diagnose(domain: Optional[str] = ...) -> None: ...
def agent(task: str, api_key: Optional[str] = ..., save_report: bool = ...) -> dict[str, Any]: ...
def optimize_file(
    filepath: str,
    auto_apply: bool = ...,
    use_llm: bool = ...,
    api_key: Optional[str] = ...,
) -> dict[str, Any]: ...
def reset_learning() -> None: ...
def explain(filepath: str, output: Optional[str] = ..., api_key: Optional[str] = ...) -> str: ...
def dashboard(port: int = ..., open_browser: bool = ...) -> None: ...
def register_backend(
    domain: str,
    name: str,
    import_path: str,
    priority: int = ...,
    tags: Optional[list[str]] = ...,
    gpu_preferred: bool = ...,
) -> None: ...
def list_backends(domain: Optional[str] = ...) -> None: ...
def share_profile(output_path: Optional[str] = ...) -> str: ...
def import_profile(filepath: str, merge: bool = ...) -> None: ...
def sync(server_url: str, machine_id: Optional[str] = ...) -> None: ...
def safe_mode(enabled: bool = ...) -> None: ...
def safe_call(domain: str, func_name: str, *args: Any, **kwargs: Any) -> Any: ...
